language: cpp
compiler:
  - gcc
#  - clang
# Make sure CMake is installed
install:
 - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo apt-get update >/dev/null
 - sudo apt-get -q install g++-4.8 cmake
 - sudo apt-get install libboost1.54-all-dev
before_script:
 - mkdir build
 - cd build
 - cmake .. $CMAKEOPTIONS
script:
 - make -j 2
after_script:
# - cd ..
# - cucumber -p verify
branches:
  only:
    - master
cache:
- apt
env:
 - CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-4.8"
 - CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-4.8"
