language: cpp
compiler:
  - gcc
before_script:
 - utils/install_deps.sh
 - mkdir build
 - cd build
 - cmake .. $CMAKEOPTIONS
script:
 - make -j2
branches:
  only:
    - master
cache:
  apt: true
  directories:
   - third_party
env:
 - CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-4.8"
 - CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-4.8"
sudo: true

