language: cpp
compiler:
  - gcc
#  - clang
# Make sure CMake is installed
install:
 - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo apt-get update >/dev/null
 - sudo apt-get -q install g++-4.8 cmake
 - sudo apt-get install libboost1.54-all-dev subversion
 - svn checkout https://svn.code.sf.net/p/simox/code/trunk simox
 - cd simox
 - mkdir build
 - cmake .. $CMAKEOPTIONS
 - make -j2
 - sudo make install
 - cd ..
 - git clone https://gitlab.com/mastermotormap/mmmcore.git
 - cd mmmcore
 - mkdir build
 - cd build
 - cmake .. $CMAKEOPTIONS
 - make -j2
 - sudo make install
before_script:
 - mkdir build
 - cd build
 - cmake .. $CMAKEOPTIONS
script:
 - make -j2
branches:
  only:
    - master
cache:
- apt
env:
 - CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-4.8"
 - CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-4.8"
sudo: true

